### ISSUE TITLE
Order Issue with PWG Stuffs plugin

### ISSUE THREAD

**Issue by HSage** [Philio/bootstrapdefault#35]
Hello there, I'm very new to all of this and I don't know much of code, but when using the piwigo plugin 'PWG Stuffs' in combination with your theme, the extra blocks that I add **before** the main block, are placed between the jumbotron and the navigation bar under the jumbotron. I think it would be better if these blocks were placed under the navigation bar? Sorry if I'm bothering you with stuff that you can't do anything about, I'm very new to this :(

**Comment by Philio** [comment]
It's quite a painful process to support many of the plugins because they
can freely inject HTML in various places within the template. In theory
it's probably possible to fix a lot of the problems with CSS, but not an
easy process. I've added support for a few popular plugins and also the
author of the Bootstrap Darkroom theme has added some and submitted PRs for
them.

I'm not familiar with this plugin so will have to install in my dev
environment and see if there is anything that can be done to improve
support.

**Comment by HSage** [comment]
Okay, hope it's easily fixable :) 
Will you post in this thread whether you can do anything about it or not? 
Appreciate the quick response :)

**Comment by HSage** [comment]
Any news on the plugin support? :)

**Comment by Philio** [comment]
@plegall added support for this, please check version 1.0.5
